#  Copyright (c) 2023 - All rights reserved.
#  Created by Curtis Poon for PROCTECH 4IT3/SEP 6IT3.
#  SoA Notice: I Curtis Poon, 400263978 certify that this material is my original work.
#  I certify that no other person's work has been used without due acknowledgement.
#  I have also not made my work available to anyone else without their due acknowledgement.

# Generated by Django 4.1.7 on 2023-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SineWaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_val', models.DecimalField(decimal_places=20, max_digits=30)),
                ('label', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_sinedata',
                'managed': False,
            },
        ),
    ]
