# Generated by Django 4.1.7 on 2023-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=30, max_digits=30)),
                ('label', models.TimeField(auto_now=True)),
            ],
        ),
    ]
