# Generated by Django 4.1.7 on 2023-04-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=25, max_digits=30)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time_stamp'],
            },
        ),
        migrations.CreateModel(
            name='SineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_val', models.DecimalField(decimal_places=20, max_digits=30)),
                ('label', models.TimeField(auto_now=True)),
            ],
        ),
    ]
