# Generated by Django 4.1.7 on 2023-02-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinedata',
            old_name='value',
            new_name='data_val',
        ),
    ]
