# Generated by Django 4.1.7 on 2023-02-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_value_sinedata_data_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinedata',
            name='data_val',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
